 export  const Actions={
    EXAM_LIST_REQUEST:"EXAM_LIST_REQUEST",
    EXAM_LIST_FAIL:"EXAM_LIST_FAIL",
    EXAM_LIST_SUCCESS:"EXAM_LIST_SUCCESS",
    EXAM_SAVE_REQUEST:"EXAM_SAVE_REQUEST",
    EXAM_SAVE_SUCCESS:"EXAM_SAVE_SUCCESS",
    EXAM_SAVE_FAIL:"EXAM_SAVE_FAIL",
    EXAM_DELETE_REQUEST:"EXAM_DELETE_REQUEST",
    EXAM_DELETE_SUCCESS:"EXAM_DELETE_SUCCESS",
    EXAM_DELETE_FAIL:"EXAM_DELETE_FAIL",


   EXAMTYPE_LIST_REQUEST:"EXAMTYPE_LIST_REQUEST",
   EXAMTYPE_LIST_FAIL:"EXAMTYPE_LIST_FAIL",
   EXAMTYPE_LIST_SUCCESS:"EXAMTYPE_LIST_SUCCESS",
   EXAMTYPE_SAVE_REQUEST:"EXAMTYPE_SAVE_REQUEST",
   EXAMTYPE_SAVE_SUCCESS:"EXAMTYPE_SAVE_SUCCESS",
   EXAMTYPE_SAVE_FAIL:"EXAMTYPE_SAVE_FAIL",
   EXAMTYPE_DELETE_REQUEST:"EXAMTYPE_DELETE_REQUEST",
   EXAMTYPE_DELETE_SUCCESS:"EXAMTYPE_DELETE_SUCCESS",
   EXAMTYPE_DELETE_FAIL:"EXAMTYPE_DELETE_FAIL",
  };